# GBA 6070 - Programming Foundation for Business Analytics
# Dr. Mohammad Salehan
# Assignment 8 - Multidimensioal Arrays
Runt the cell below to set up your notebook. Each cell should start with np.random.seed(0) to make the results consistent for all students.

In [96]:
import numpy as np
np.random.seed(0)

1. Create a 4x4 array that contains numbers 1-16.

In [97]:
np.random.seed(0)
x=np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

2. Create 2 random 4x3 arrays and calculate the sum of their corrosponding elements. Use vectorization for sum calculation.

In [98]:
np.random.seed(0)
x1=np.random.random((4,3))
x2=np.random.random((4,3))
print(x1)
print(x2)
x3=x1+x2
x3

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]
[[0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]]


array([[1.11685807, 1.640786  , 0.67379943],
       [0.63201248, 0.4438732 , 1.47851396],
       [1.21574396, 1.76178515, 1.9422811 ],
       [1.18260008, 1.2532044 , 1.3094241 ]])

3. Create 2 normally distributed (mean=0, std_dev=1) random 10x5 arrays, stack them vertically, then calculate the average of each column. Use vectorization.

In [99]:
np.random.seed(0)
a=np.random.normal(0,1,(10,5))
b=np.random.normal(0,1,(10,5))
c=np.vstack([a,b])
print(c)
np.mean(c,axis=0)

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]
 [-0.89546656  0.3869025  -0.51080514 -1.18063218 -0.02818223]
 [ 0.42833187  0.06651722  0.3024719  -0.63432209 -0.36274117]
 [-0.67246045 -0.35955316 -0.81314628 -1.7262826   0.17742614]
 [-0.40178094 -1.63019835  0.46278226 -0.90729836  0.0519454 ]
 [ 0.72909056  0.12898291  1.13940068 -1.23482582  0.40234164]
 [-0.68481009 -0.87079715 -0.57884966 -0.31155253  0.05

array([-0.2190577 ,  0.24840102,  0.18640318, -0.30832866,  0.39162224])

4. Create a normally distributed (mean=0, std_dev=1) random 10x5 array, then calculate the sum of the values in each row. Use vectorization.

In [100]:
np.random.seed(0)
h=np.random.normal(0,1,(10,5))
print(h)
np.sum(h,axis=1)

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]]


array([ 7.25139873,  0.12883298,  2.92489305,  1.0815671 ,  0.49265458,
        1.40634698, -2.68338442,  1.89938993, -2.73371788, -2.74001743])

5. Create a 5x3 array initialized with random integers 1-10, then reshape it to 3x5, and then calculate its sum (single number fo sum). Use vectorization.

In [101]:
np.random.seed(0)
e=np.random.randint(1,11,(5,3))
print(e)
print(e.T)
print(np.sum(e.T))

[[ 6  1  4]
 [ 4  8 10]
 [ 4  6  3]
 [ 5  8  7]
 [ 9  9  2]]
[[ 6  4  4  5  9]
 [ 1  8  6  8  9]
 [ 4 10  3  7  2]]
86


6. Create a 5x3 array initialized with random integers 1-10, then multiply each value by 2. Use vectorization.

In [102]:
np.random.seed(0)
f=np.random.randint(1,11,(5,3))
print(f)
f*2

[[ 6  1  4]
 [ 4  8 10]
 [ 4  6  3]
 [ 5  8  7]
 [ 9  9  2]]


array([[12,  2,  8],
       [ 8, 16, 20],
       [ 8, 12,  6],
       [10, 16, 14],
       [18, 18,  4]])